<?php
namespace Database\Seeders;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        // Define category-wise products
        $categoriesWithProducts = [
            'Living Room' => [
                "Couch", "Table", "TV", "Sideboard", "Chair", "Couch table", "Shelf", "Armchair",
                "Plant", "Carpet", "Floor lamp", "Wardrobe", "Corner couch", "Drawer", "Lamp system",
                "Picture", "Modern wall unit", "Ceiling light", "Aquarium", "Fan", "Guitar",
                "Kid's toy (big)", "Drying rack", "Sunshade", "Ladder", "Clothes rack", "Air conditioner",
                "Trampoline", "Washbasin cabinets", "Houseplant", "Bed", "Lamp", "Piano", "Grand Piano",
                "Keyboard", "Drums", "Digital Piano", "Basket", "Additional mattress", "Baby buggy",
                "Suitcase", "Hatstand", "Tea-cart", "Bedding box", "Ironing board", "Boxspring bed",
                "House bar", "Bunk bed", "Sculpture", "Wall clock", "Loft bed", "Long case clock",
                "Canopy bed", "Flower pot", "Safe", "Baby crib", "Waterbed", "Weight bench & weights",
                "Rowing machine", "Folding bed", "Surf board", "Treadmill", "Single bed", "Crosstrainer",
                "Washing machine", "Hometrainer", "Laundry basket", "Bicycle adult", "Vacuum cleaner",
                "Bicycle child", "Wine refrigerator", "Tricycle / tractor", "Camping-set", "Freezer cabinet",
                "Ski / Snowboard", "Tumbler", "Skibox", "Deep-freezer", "Refrigerator", "Dishwasher",
                "Printer / copier", "Microwave", "Amplifier", "Record player", "Loudspeakers",
                "Computer / Accessories", "Stereo system", "Wardrobe with sliding doors", "Bedside lamp",
                "Chandelier", "Table lamp", "Corner office desk", "Korpus", "Buffet", "Folding table",
                "Country wardrobe", "Folding wardrobe", "Garden table", "Roller shutter cabinet",
                "Side table", "Showcase", "Bureau", "Small stool", "Changing table", "Couch bed",
                "Classic wall unit", "Baby chair", "Office chair", "Stool", "Desk", "Tire", "Shoe closet",
                "Nightstand", "Mirror", "Grill", "Gardenchair", "Chest", "Cat tree", "Bench", "Double bed"
            ],
            'Bedroom' => [
                "Double bed", "Single bed", "Drawer", "Wardrobe", "Wardrobe with sliding doors", "Shelf",
                "Nightstand", "Chair", "Sideboard", "Mirror", "Desk", "Bedside lamp", "Boxspring bed",
                "Ceiling light", "Carpet", "Picture", "TV", "Table", "Aquarium", "Air conditioner",
                "Clothes rack", "Fan", "Ladder", "Drying rack", "Sunshade", "Kid's toy (big)", "Guitar",
                "Trampoline", "Washbasin cabinets", "Houseplant", "Bed", "Lamp", "Piano", "Grand Piano",
                "Keyboard", "Drums", "Digital Piano", "Basket", "Additional mattress", "Baby buggy",
                "Suitcase", "Hatstand", "Teacart", "Bedding box", "Ironing board", "House bar", "Bunk bed",
                "Sculpture", "Wall clock", "Loft bed", "Long case clock", "Canopy bed", "Flower pot",
                "Safe", "Baby crib", "Waterbed", "Weight bench & weights", "Rowing machine", "Folding bed",
                "Surf board", "Treadmill", "Crosstrainer", "Washing machine", "Hometrainer", "Laundry basket",
                "Bicycle adult", "Vacuum cleaner", "Bicycle child", "Wine refrigerator", "Tricycle / tractor",
                "Campingset", "Freezer cabinet", "Ski / Snowboard", "Tumbler", "Skibox", "Deepfreezer",
                "Refrigerator", "Dishwasher", "Printer / copier", "Microwave", "Amplifier", "Record player",
                "Loudspeakers", "Computer / Accessories", "Stereo system", "Floor lamp", "Chandelier",
                "Table lamp", "Corner office desk", "Korpus", "Buffet", "Modern wall unit", "Folding table",
                "Country wardrobe", "Folding wardrobe", "Garden table", "Roller shutter cabinet",
                "Side table", "Showcase", "Bureau", "Small stool", "Changing table", "Couch bed",
                "Classic wall unit", "Corner couch", "Baby chair", "Office chair", "Stool", "Lamp system",
                "Tire", "Shoe closet", "Grill", "Gardenchair", "Chest", "Cat tree", "Bench", "Plant",
                "Couch table", "Armchair", "Couch"
            ],

            "Dining Room" => [
                "Table","Chair","Sideboard","Shelf","Drawer","Plant","Lamp system","Carpet","Wardrobe","Baby chair","Wall clock","Picture","Ceiling light","Floor lamp","Houseplant","TV","Chandelier","Teacart","Drying rack","Sunshade","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Additional mattress","Baby buggy","Suitcase","Hatstand","Bedding box","Ironing board","Boxspring bed","House bar","Bunk bed","Sculpture","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Bicycle adult","Vacuum cleaner","Bicycle child","Wine refrigerator","Tricycle / tractor","Campingset","Freezer cabinet","Ski / Snowboard","Tumbler","Skibox","Deepfreezer","Refrigerator","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Bedside lamp","Table lamp","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Office chair","Stool","Desk","Tire","Shoe closet","Nightstand","Mirror","Grill","Gardenchair","Chest","Cat tree","Bench","Couch table","Armchair","Couch","Double bed",
            ],
            "Kitchen"=> [
                "Table","Chair","Shelf","Wall clock","Microwave","Drawer","Sideboard","Wardrobe","Vacuum cleaner","Refrigerator","Deepfreezer","Houseplant","Carpet","Lamp system","Stool","Ceiling light","Teacart","House bar","Drying rack","Sunshade","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Additional mattress","Baby buggy","Suitcase","Hatstand","Bedding box","Ironing board","Boxspring bed","Bunk bed","Sculpture","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Bicycle adult","Bicycle child","Wine refrigerator","Tricycle / tractor","Campingset","Freezer cabinet","Ski / Snowboard","Tumbler","Skibox","Dishwasher","Printer / copier","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Floor lamp","Bedside lamp","Chandelier","Table lamp","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Baby chair","Office chair","Desk","Tire","Shoe closet","Picture","Nightstand","Mirror","Grill","Gardenchair","Chest","Cat tree","Bench","TV","Plant","Couch table","Armchair","Couch","Double bed",
            ],
           " Bathroom & Hallway"=> [
               "Shelf","Drawer","Shoe closet","Mirror","Sideboard","Wardrobe","Carpet","Picture","Hatstand","Side table","Ceiling light","Floor lamp","Washing machine","Tumbler","Lamp system","Stool","Laundry basket","Plant","Washbasin cabinets","Ladder","Drying rack","Sunshade","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Additional mattress","Baby buggy","Suitcase","Teacart","Bedding box","Ironing board","Boxspring bed","House bar","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Hometrainer","Bicycle adult","Vacuum cleaner","Bicycle child","Wine refrigerator","Tricycle / tractor","Campingset","Freezer cabinet","Ski / Snowboard","Skibox","Deepfreezer","Refrigerator","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Bedside lamp","Chandelier","Table lamp","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Baby chair","Office chair","Desk","Tire","Nightstand","Grill","Gardenchair","Chest","Cat tree","Bench","TV","Couch table","Table","Armchair","Chair","Couch","Double bed",
           ],
            "Office"=> [
                "Desk","Table","Office chair","Chair","Wardrobe","Shelf","Drawer","Sideboard","Korpus","Printer / copier","Computer / Accessories","Couch","Armchair","Couch bed","Picture","Ceiling light","Floor lamp","Lamp system","Drying rack","Sunshade","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Additional mattress","Baby buggy","Suitcase","Hatstand","Teacart","Bedding box","Ironing board","Boxspring bed","House bar","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Bicycle adult","Vacuum cleaner","Bicycle child","Wine refrigerator","Tricycle / tractor","Campingset","Freezer cabinet","Ski / Snowboard","Tumbler","Skibox","Deepfreezer","Refrigerator","Dishwasher","Microwave","Amplifier","Record player","Loudspeakers","Stereo system","Wardrobe with sliding doors","Bedside lamp","Chandelier","Table lamp","Corner office desk","Buffet","Modern wall unit","Folding table","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Classic wall unit","Corner couch","Baby chair","Stool","Tire","Shoe closet","Nightstand","Mirror","Grill","Gardenchair","Chest","Cat tree","Carpet","Bench","TV","Plant","Couch table","Double bed",
            ],
            "Attic"=> [
                "Shelf","Wardrobe","Folding wardrobe","Suitcase","Additional mattress","Bicycle adult","Bicycle child","Floor lamp","Table","TV","Drawer","Couch table","Carpet","Chest","Mirror","Picture","Shoe closet","Table lamp","Drying rack","Sunshade","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Baby buggy","Hatstand","Tea-cart","Bedding box","Ironing board","Boxspring bed","House bar","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Vacuum cleaner","Wine refrigerator","Tricycle / tractor","Camping-set","Freezer cabinet","Ski / Snowboard","Tumbler","Skibox","Deep-freezer","Refrigerator","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Bedside lamp","Chandelier","Ceiling light","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Baby chair","Office chair","Stool","Desk","Lamp system","Tire","Nightstand","Grill","Gardenchair","Cat tree","Bench","Plant","Sideboard","Armchair","Chair","Couch","Double bed",
            ],
           " Basement"=> [
               "Shelf","Folding wardrobe","Bicycle adult","Bicycle child","Suitcase","Wardrobe","Table","Chair","Tire","Ski / Snowboard","Drawer","Sideboard","Shoe closet","Refrigerator","Deepfreezer","Freezer cabinet","Chest","Stool","Sunshade","Drying rack","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Additional mattress","Baby buggy","Hatstand","Teacart","Bedding box","Ironing board","Boxspring bed","House bar","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Vacuum cleaner","Wine refrigerator","Tricycle / tractor","Campingset","Tumbler","Skibox","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Floor lamp","Bedside lamp","Chandelier","Ceiling light","Table lamp","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Baby chair","Office chair","Desk","Lamp system","Picture","Nightstand","Mirror","Grill","Gardenchair","Cat tree","Carpet","Bench","TV","Plant","Couch table","Armchair","Couch","Double bed",
           ],
            "Garage"=> [
                "Tire","Shelf","Bicycle adult","Bicycle child","Wardrobe","Table","Chair","Drawer","Ski / Snowboard","Skibox","Chest","Mirror","Shoe closet","Stool","Stereo system","Freezer cabinet","House bar","Drums","Sunshade","Drying rack","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Digital Piano","Basket","Additional mattress","Baby buggy","Suitcase","Hatstand","Teacart","Bedding box","Ironing board","Boxspring bed","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Vacuum cleaner","Wine refrigerator","Tricycle / tractor","Campingset","Tumbler","Deepfreezer","Refrigerator","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Wardrobe with sliding doors","Floor lamp","Bedside lamp","Chandelier","Ceiling light","Table lamp","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Baby chair","Office chair","Desk","Lamp system","Picture","Nightstand","Grill","Gardenchair","Cat tree","Carpet","Bench","TV","Plant","Sideboard","Couch table","Armchair","Couch","Double bed",
            ],
            "Garden / Balcony"=> [
                "Chair","Table","Grill","Plant","Gardenchair","Garden table","Couch","Couch table","Flower pot","Shelf","Bench","Folding table","Armchair","Chest","Stool","Sculpture","Basket","Campingset","Trampoline","Sunshade","Drying rack","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Additional mattress","Baby buggy","Suitcase","Hatstand","Teacart","Bedding box","Ironing board","Boxspring bed","House bar","Bunk bed","Wall clock","Loft bed","Long case clock","Canopy bed","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Laundry basket","Bicycle adult","Vacuum cleaner","Bicycle child","Wine refrigerator","Tricycle / tractor","Freezer cabinet","Ski / Snowboard","Tumbler","Skibox","Deepfreezer","Refrigerator","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Floor lamp","Bedside lamp","Chandelier","Wardrobe","Ceiling light","Table lamp","Corner office desk","Korpus","Buffet","Modern wall unit","Country wardrobe","Folding wardrobe","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Changing table","Couch bed","Classic wall unit","Corner couch","Baby chair","Office chair","Desk","Lamp system","Tire","Shoe closet","Picture","Nightstand","Mirror","Cat tree","Carpet","Drawer","TV","Sideboard","Double bed",
            ],
            "Nursery"=> [
                "Wardrobe","Wardrobe with sliding doors","Drawer","Baby crib","Shelf","Changing table","Carpet","Ceiling light","Floor lamp","Plant","Baby chair","Tricycle / tractor","Mirror","Chest","Table lamp","Bedding box","Laundry basket","Stool","Kid's toy (big)","Drying rack","Sunshade","Ladder","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Basket","Additional mattress","Baby buggy","Suitcase","Hatstand","Teacart","Ironing board","Boxspring bed","House bar","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Washing machine","Hometrainer","Bicycle adult","Vacuum cleaner","Bicycle child","Wine refrigerator","Campingset","Freezer cabinet","Ski / Snowboard","Tumbler","Skibox","Deepfreezer","Refrigerator","Dishwasher","Printer / copier","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Bedside lamp","Chandelier","Corner office desk","Korpus","Buffet","Modern wall unit","Folding table","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Small stool","Couch bed","Classic wall unit","Corner couch","Office chair","Desk","Lamp system","Tire","Shoe closet","Picture","Nightstand","Grill","Gardenchair","Cat tree","Bench","TV","Sideboard","Couch table","Table","Armchair","Chair","Couch","Double bed",
            ],
            "Storeroom"=> [
                "Shelf","Ironing board","Vacuum cleaner","Drawer","Washing machine","Tumbler","Carpet","Mirror","Stool","Baby chair","Small stool","Folding table","Korpus","Printer / copier","Laundry basket","Hometrainer","Additional mattress","Basket","Drying rack","Sunshade","Ladder","Kid's toy (big)","Guitar","Fan","Clothes rack","Air conditioner","Trampoline","Aquarium","Washbasin cabinets","Houseplant","Bed","Lamp","Piano","Grand Piano","Keyboard","Drums","Digital Piano","Baby buggy","Suitcase","Hatstand","Teacart","Bedding box","Boxspring bed","House bar","Bunk bed","Sculpture","Wall clock","Loft bed","Long case clock","Canopy bed","Flower pot","Safe","Baby crib","Waterbed","Weight bench & weights","Rowing machine","Folding bed","Surf board","Treadmill","Single bed","Crosstrainer","Bicycle adult","Bicycle child","Wine refrigerator","Tricycle / tractor","Campingset","Freezer cabinet","Ski / Snowboard","Skibox","Deepfreezer","Refrigerator","Dishwasher","Microwave","Amplifier","Record player","Loudspeakers","Computer / Accessories","Stereo system","Wardrobe with sliding doors","Floor lamp","Bedside lamp","Chandelier","Wardrobe","Ceiling light","Table lamp","Corner office desk","Buffet","Modern wall unit","Country wardrobe","Folding wardrobe","Garden table","Roller shutter cabinet","Side table","Showcase","Bureau","Changing table","Couch bed","Classic wall unit","Corner couch","Office chair","Desk","Lamp system","Tire","Shoe closet","Picture","Nightstand","Grill","Gardenchair","Chest","Cat tree","Bench","TV","Plant","Sideboard","Couch table","Table","Armchair","Chair","Couch","Double bed",
            ],


        ];

        foreach ($categoriesWithProducts as $categoryName => $products) {
            $category = Category::firstOrCreate(['name' => $categoryName]);

            foreach ($products as $productName) {
                $product = Product::firstOrCreate(['name' => $productName]);

                // Attach product to category (avoid duplicates)
                $product->categories()->syncWithoutDetaching([$category->id]);
            }
        }
    }
}
